version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/productsdb
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pgdata:
